version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: software.amazon.awssdk:sqs
    versions:
    - 2.15.69
    - 2.15.73
    - 2.15.77
    - 2.15.81
    - 2.16.13
    - 2.16.18
    - 2.16.23
    - 2.16.29
    - 2.16.3
    - 2.16.34
    - 2.16.39
    - 2.16.43
    - 2.16.8
  - dependency-name: jvm
    versions:
    - 1.4.21-2
    - 1.4.30
    - 1.4.31
    - 1.4.32
  - dependency-name: org.jetbrains.dokka
    versions:
    - 1.4.20
    - 1.4.30
  - dependency-name: io.mockk:mockk
    versions:
    - 1.10.6
  - dependency-name: org.jlleitschuh.gradle.ktlint
    versions:
    - 9.4.1
